# Generated by Django 4.2.27 on 2025-12-16 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('fecha_fundacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Fundación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='eventos.deporte', verbose_name='Deporte')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
    ]
